version: '3.3'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      TZ: 'America/Sao_Paulo'
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: '3308'
    ports:
      - '3308:3308'
    expose:
      - '3308'
    networks:
      - home-network
  zipkin-server:
    image: openzipkin/zipkin:2.23.2
    ports:
      - 9411:9411
    networks:
      - home-network
  naming-server:
    image: jonasjrf/naming-server:v1
    ports:
      - 8761:8761
    networks:
      - home-network
  api-gateway:
    image: jonasjrf/api-gateway:v1
    ports:
      - 8765:8765
    depends_on:
      - naming-server
    environment:
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
    networks:
      - home-network
networks:
  home-network:
    driver: bridge
